# stage builder
FROM node:16-slim as builder
WORKDIR /usr/src/app

# package*.json, tsconfig*.json, tslint.json
COPY *.json ./
RUN npm ci

# because frontend has reference on backend
COPY backend/ backend/
COPY src/ src/

ARG NG_CONFIG=production
RUN npx ng build --configuration $NG_CONFIG

# stage run-time
FROM nginx:stable-alpine
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
