version: '2.1'
jobs:
  build:
    docker:
      - image: 'cimg/node:16.13'
    resource_class: medium

    parameters:
      app_path:
        description: "is it backend or frontend path?"
        default: "backend"
        type: string

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Environment.CACHE_VERSION }}-{{ checksum "<< parameters.app_path >>/package-lock.json" }}
      - run: ls -l << parameters.app_path >>/
      - run: |
          cd << parameters.app_path >>
          npm ci
          npm run build
          ls -l

      # cache for across pipelines
      - save_cache:
          key: deps-{{ .Environment.CACHE_VERSION }}-{{ checksum "<< parameters.app_path >>/package-lock.json" }}
          paths: 
            - << parameters.app_path >>/node_modules

      # cache for subsequent jobs
      - persist_to_workspace:
          root: .
          paths:
            - << parameters.app_path >>/
  test:
    docker:
      - image: 'cimg/node:16.13'
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - run: ls -l backend/

workflows:
  backend:
    jobs:
      - build:
          app_path: backend
      - test:
          requires:
            - build
  frontend:
    jobs:
      - build:
          app_path: frontend
      - test:
          requires:
            - build
