version: '2.1'
jobs:
  build:
    docker:
      - image: 'cimg/node:16.13'
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "backend/package-lock.json" }}
      - run: ls -l backend/
      - run: |
          cd backend
          npm ci
          npm run build
          ls -l

      # cache for across pipelines
      - save_cache:
          key: v1-deps-{{ checksum "backend/package-lock.json" }}
          paths: 
            - node_modules
  test:
    docker:
      - image: 'cimg/node:16.13'
    resource_class: small
    steps:
      - run: ls -l backend/

workflows:
  backend:
    jobs:
      - build
      - test:
          requires:
            - build
