version: '2.1'
orbs:
  node: circleci/node@5.0.0
jobs:
  build:
    docker:
      - image: 'cimg/node:16.13'
    steps:
      - checkout
      - run: 
          command: cd frontend
      - node/install-packages:
          app-dir: ~/project/backend
      - run: ls -l
      - run : echo "foo test"
workflows:
  backend:
    jobs:
      - build
