export class AppMenuModel {
  appMenu = [    {
      id: 'lock_open',
      name: 'Login | Sign up',
      tags: 'for an inseri account',
      color: 'green',
      status: 'stable',
      appType: 'login',
      description: 'Login or create an account',
      showOnHome: true,
      appGroup: 'admin'
    },
    {
      id: 'aspect_ratio',
      name: 'HTML Viewer ',
      tags: 'html, css, plaintext ',
      color: 'green',
      status: 'stable',
      appType: 'htmlViewer',
      description: 'It displays HTML snippets and applies externally defined styles to the view.',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'blur_on',
      name: 'Machine Reasoning',
      tags: 'N3, rdfs, rdf, owl',
      color: 'yellow',
      status: 'under development',
      appType: 'machineReasoning',
      description: 'Reason with reason',
      showOnHome: false,
      appGroup: 'microservice'
    },
    {
      id: 'speaker_notes',
      name: 'Comment App',
      tags: 'comment, browse',
      color: 'green',
      status: 'stable',
      appType: 'commentOnIndices',
      description: 'Comment on pages of books, etc',
      showOnHome: false,
      appGroup: 'add'
    },
/*    {
      id: 'calendar_today',
      name: 'Calendar App',
      tags: 'admin',
      color: 'red',
      status: 'under development',
      appType: 'calendar',
      description: 'Your calendar',
      showOnHome: false,
      appGroup: 'add'
    },*/
    {
      id: 'input',
      name: 'Json Environment ',
      tags: 'json, python ',
      color: 'green',
      status: 'stable',
      appType: 'jsonEnvironment',
      description: 'Microservice for json manipulations',
      showOnHome: false,
      appGroup: 'microservice'
    },
    {
      id: 'audiotrack',
      name: 'Audio Payer',
      tags: 'wav, mp3, etc',
      color: 'green',
      status: 'stable',
      appType: 'audioPlayer',
      description: 'Play your audiofiles',
      showOnHome: false,
      appGroup: 'application'
    },
    {
      id: 'folder',
      name: 'My Files',
      tags: 'files, folders and queries',
      color: 'yellow',
      status: 'under development',
      appType: 'myFiles',
      description: 'files, folders and queries',
      showOnHome: false,
      appGroup: 'add'
    },
    {
      id: 'format_size',
      name: 'Text Editor',
      tags: 'primefaces, quill',
      color: 'green',
      status: 'stable',
      appType: 'primeEditor',
      description: 'Write and Save text on a page',
      showOnHome: true,
      appGroup: 'add'
    },
    {
      id: 'short_text',
      name: 'Plaintext Viewer ',
      tags: 'plaintext, html without css ',
      color: 'green',
      status: 'stable',
      appType: 'textlistViewers',
      description: undefined,
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'format_paint',
      name: 'PaintCanvas',
      tags: 'draw your notes',
      color: 'green',
      status: 'stable',
      appType: 'paint',
      description: undefined,
      showOnHome: true,
      appGroup: 'visualise'
    },
    // {
    //   id: 'line_style',
    //   name: 'SVG-Transcription',
    //   tags: 'diplomatic transcription, text',
    //   color: 'orange',
    //   status: 'under development',
    //   appType: 'svgTranscription',
    //   description: ' SVG transcription with exact word positions',
    //   showOnHome: false,
    //   appGroup: 'visualise'
    // },
    // {
    //   id: 'view_week',
    //   name: 'Parzival - Fassung',
    //   tags: 'synopsis, text, version',
    //   color: 'green',
    //   status: 'stable',
    //   appType: 'parzivalFassung',
    //   description: 'Project specific App for the Parzival Project - Open more than one app of this type to test it!',
    //   showOnHome: false,
    //   appGroup: 'visualise'
    // },
    // {
    //   id: 'turned_in',
    //   name: 'AVP-Edition',
    //   tags: 'synopsis, text, version',
    //   color: 'orange',
    //   status: 'under development',
    //   appType: 'avpEditionView',
    //   description: 'Project specific App for the AVP Project',
    //   showOnHome: false,
    //   appGroup: 'visualise'
    // },
    {
      id: 'album',
      name: 'OpenBis Login',
      tags: 'login, query, third party token',
      color: 'green',
      status: 'stable',
      appType: 'openbisLogin',
      description: 'Set token for OpenBis',
      showOnHome: false,
      appGroup: 'admin'
    },
    {
      id: 'image',
      name: 'Image Viewer',
      tags: 'image, zoom, iif',
      color: 'green',
      status: 'stable',
      appType: 'imageViewer',
      description: 'Display and zoom in images',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'add_photo_alternate',
      name: 'Simple Image App',
      tags: 'image',
      color: 'green',
      status: 'stable',
      appType: 'simpleImageApp',
      description: 'Display simple images',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'view_list',
      name: 'Data list viewer',
      tags: 'generic, list, configurable',
      color: 'green',
      status: 'stable',
      appType: 'dataListView',
      description: 'Display simple images',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'subdirectory_arrow_right',
      name: 'Tree hierarchical-navigation-view',
      tags: 'navigation',
      color: 'green',
      status: 'stable',
      appType: 'treeNavigation',
      description: ' This app can be combined with apps for resource view.',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'video_library',
      name: 'Youtube Video Viewer',
      tags: 'video',
      color: 'green',
      status: 'stable',
      appType: 'youtubeVideo',
      description: ' You can embed youtube - videos in this app.',
      showOnHome: true,
      appGroup: 'application'
    },
    {
      id: 'art_track',
      name: 'Synopsis Viewer',
      tags: 'synopsis, light table',
      color: 'orange',
      status: 'under development',
      appType: 'synopsisViewer',
      description: 'Open and compare different images and text',
      showOnHome: false,
      appGroup: 'application'
    },
    {
      id: 'spa',
      name: 'Json Viewer',
      tags: 'json tree',
      color: 'green',
      status: 'stable',
      appType: 'jsonViewer',
      description: 'This app visualizes json objects as a tree.',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'bar_chart',
      name: 'Bar Chart',
      tags: 'd3.js, interactive',
      color: 'orange',
      status: 'under development',
      appType: 'barCharts',
      description: 'To define data with two dimensions',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'bar_chart',
      name: 'Grouped Bar Chart V2',
      tags: 'd3.js, interactive',
      color: 'green',
      status: 'stable',
      appType: 'groupedBarChartV2',
      description: 'To define data with two dimensions',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'show_chart',
      name: 'Line Chart',
      tags: 'd3.js, interactive',
      color: 'orange',
      status: 'under development',
      appType: 'lineCharts',
      description: 'To define data with two dimensions',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'insert_chart_outlined',
      name: 'Brush Zoom',
      tags: 'd3.js, interactive',
      color: 'orange',
      status: 'under development',
      appType: 'brushZoomCharts',
      description: 'To define data with two dimensions',
      showOnHome: false,
      appGroup: 'visualisation'
    },
    {
      id: 'add_location',
      name: 'Leaflet map',
      tags: 'geo data visualisation',
      color: 'orange',
      status: 'under development',
      appType: 'leafletMaps',
      description: 'Visualize data on maps',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'pie_chart',
      name: 'Pie Chart',
      tags: 'd3.js, data visualisation',
      color: 'orange',
      status: 'under development',
      appType: 'pieCharts',
      description: 'To visualise subsets',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'pie_chart',
      name: 'Pie Chart V2',
      tags: 'd3.js, data visualisation',
      color: 'orange',
      status: 'under development',
      appType: 'pieChartsV2',
      description: 'To visualise subsets',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'multiline_chart',
      name: 'Radial Bar Chart',
      tags: 'd3.js, data visualisation',
      color: 'orange',
      status: 'under development',
      appType: 'radialBarCharts',
      description: 'For two dimensional data',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'linear_scale',
      name: 'Sankey',
      tags: 'd3.js, data visualisation',
      color: 'orange',
      status: 'under development',
      appType: 'sankeyCharts',
      description: ' To display dependent data',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'subtitles',
      name: ' Stacked Bar Chart',
      tags: 'd3.js, data visualisation',
      color: 'orange',
      status: 'under development',
      appType: 'stackedBarCharts',
      description: 'To display grouped sets',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'all_out',
      name: 'Chord diagram',
      tags: 'd3.js, data visualisation',
      color: 'orange',
      status: 'under development',
      appType: 'chordDiagrams',
      description: 'To compare intensity of connections',
      showOnHome: false,
      appGroup: 'visualise'
    },
    // {
    //   id: 'add_to_queue',
    //   name: 'Knora Resource Creation',
    //   tags: 'knora, data entry',
    //   color: 'orange',
    //   status: 'under development',
    //   appType: 'createResourceForm',
    //   description: 'With this app you can create data in Knora.',
    //   showOnHome: false,
    //   appGroup: 'add'
    // },
    // {
    //   id: 'web',
    //   name: 'Knora Edit Resource',
    //   tags: 'knora, data manipulation',
    //   color: 'orange',
    //   status: 'under development',
    //   appType: 'editResourceForm',
    //   description: 'With this app you can change data in Knora and see the history of given properties.',
    //   showOnHome: false,
    //   appGroup: 'add'
    // },
    // {
    //   id: 'web',
    //   name: 'Nested Resource Viewer',
    //   tags: 'knora',
    //   color: 'orange',
    //   status: 'under development',
    //   appType: 'knoraV2viewer',
    //   description: 'With this app you can easily look at a Knora resource.',
    //   showOnHome: false,
    //   appGroup: 'visualise'
    // },
    {
      id: 'aspect_ratio',
      name: 'Joined Text View',
      tags: 'knora, text, html',
      color: 'orange',
      status: 'under development',
      appType: 'joinedTextView',
      description: 'Map text resources to blocks, lines and words and show them as HTML',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'drag_indicator',
      name: 'Sparql - Visualiser',
      tags: 'sparql, rdf, rdfs, owl',
      color: 'green',
      status: 'stable',
      appType: 'sparqlVisualizer',
      description: 'Visualize Ontologies and RDF/RDFS/Owl data',
      showOnHome: true,
      appGroup: 'application'
    },
    {
      id: 'view_week',
      name: 'Crispr',
      tags: 'crispr',
      color: 'green',
      status: 'stable',
      appType: 'crispr',
      description: 'Try your data with the crispr algorithm',
      showOnHome: true,
      appGroup: 'application'
    },
    {
      id: 'camera_enhance',
      name: 'Salsah 2',
      tags: 'DaSCH',
      color: 'orange',
      status: 'deprecated',
      appType: 'salsah2',
      description: 'Predecessor of Kuirl / SUID',
      showOnHome: true,
      appGroup: 'application'
    },
    {
      id: 'subdirectory_arrow_right',
      name: 'Hierarchical hierarchical-navigation-view',
      tags: 'knora, hierarchical-navigation-view',
      color: 'orange',
      status: 'under development',
      appType: 'hierarchicalNavigationView',
      description: 'Map resources in a graph to a hierarchical-navigation-view tree.',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'table_chart',
      name: 'Spreadsheet',
      tags: 'spreadsheet you will love',
      color: 'orange',
      status: 'under development',
      appType: 'spreadSheet',
      description: 'Your spreadsheet',
      showOnHome: true,
      appGroup: 'add'
    },
    {
      id: 'book',
      name: 'Anton Webern Gesamtausgabe',
      tags: 'Anton Webern',
      color: 'green',
      status: 'stable',
      appType: 'webern',
      description: 'Anton Webern App',
      showOnHome: true,
      appGroup: 'application'
    },
    {
      id: 'book',
      name: 'iframe',
      tags: 'iframe',
      color: 'green',
      status: 'stable',
      appType: 'iframe',
      description: 'iframe',
      showOnHome: false,
      appGroup: 'application'
    },
    {
      id: 'book',
      name: 'Kuno Raeber Online Edition',
      tags: 'raeber',
      color: 'green',
      status: 'stable',
      appType: 'raeber',
      description: 'raeber app',
      showOnHome: true,
      appGroup: 'application'
    },
    {
      id: 'horizontal_split',
      name: 'Url update app',
      tags: 'url',
      color: 'green',
      status: 'stable',
      appType: 'urlUpdate',
      description: 'urlUpdate',
      showOnHome: false,
      appGroup: 'application'
    },
    {
      id: 'horizontal_split',
      name: 'pdf viewer',
      tags: 'pdf',
      color: 'green',
      status: 'stable',
      appType: 'pdfViewer',
      description: 'pdfViewer',
      showOnHome: false,
      appGroup: 'application'
    },
    {
      id: 'select_all',
      name: 'Key Value',
      tags: 'key value',
      color: 'green',
      status: 'stable',
      appType: 'keyValue',
      description: 'keyValue',
      showOnHome: false,
      appGroup: 'visualise'
    },
    {
      id: 'open_in_browser',
      name: 'Browserling',
      tags: 'browser virtualisation',
      color: 'green',
      status: 'stable',
      appType: 'browserling',
      description: 'browserling',
      showOnHome: false,
      appGroup: 'application'
    },
    {
      id: 'book',
      name: 'GND Subscriber',
      tags: 'gnd url param subscriber',
      color: 'green',
      status: 'stable',
      appType: 'gndSubscriber',
      description: 'gnd',
      showOnHome: false,
      appGroup: 'application'
    },
    {
      id: 'leak_add',
      name: 'Url Param Updater',
      tags: 'generic url updater',
      color: 'red',
      status: 'under development',
      appType: 'urlParamUpdater',
      description: 'gnd',
      showOnHome: false,
      appGroup: 'application'
    }
  ];
}
